#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

#if [ "${grub-platform}" == "pc" ]; then
#	menuentry "Microsoft Windows BIOS/MBR" {
#		insmod part_msdos
#		insmod ntfs
#		insmod ntldr
#		search --no-floppy --fs-uuid --set=root --hint-bios=hd0,msdos1 --hint-efi=hd0,msdos1 --hint-baremetal=ahci0,msdos1 BE48DE8E48DE44B5
#		ntldr /bootmgr
#	}
#fi

menuentry "System Shutdown" {
	echo "System shutting down..."
	halt
}

menuentry "System Reboot" {
	echo "System rebooting..."
	reboot
}

